### ISSUE TITLE
問題用のページUIについて

### ISSUE THREAD

**Issue by Cell1729** [CloudWordCreator/CloudWordCreator#15]
## 固定ヘッダーを作成する

現在はスクロールをすると種類切り替えボタン、印刷用のボタンが隠れてしまうが固定して表示したい

## コード

htmlファイル
戻るボタンのURLは要修正
```html
    <div class="header fixed-header">
        <button id="english-to-japanese-button" class="button">英語→日本語</button>
        <button id="japanese-to-english-button" class="button">日本語→英語</button>
        <button onclick="printContent()" class="button">印刷</button>
        <a href="{% url 'display_data' %}">戻る</a>
    </div>
```

css
```css
body {
    padding-top: 60px; /* Adjust this value based on the height of your fixed header */
}

.fixed-header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background-color: white; /* Optional: to ensure the header has a background */
    z-index: 1000; /* Ensure it is above other content */
    padding: 10px; /* Optional: adjust padding as needed */
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Optional: add a shadow for better visibility */
}
```
