### ISSUE TITLE
印刷設定について

### ISSUE THREAD

**Issue by Cell1729** [CloudWordCreator/CloudWordCreator#2]
media="print"とすると印刷用のCSSとなる。

```html
<link href="css/print.css" media="print" rel="stylesheet" type="text/css" />
```

ヘッダーを消す

```css
@page {
	margin: 0mm 5mm;
	size: A4 portrait; //横の場合はlandscape
}
```

A4縦の大きさは210mm×297mm

```html
<div class="printer-setting">
中身は省略
</body>
```

```css
.salary {
	padding-top: 5mm;
	width: 210mm;
	height: 297mm;
}
```

[参考](https://qiita.com/e-sato/items/68470a4203f6abfaa801)

**Comment by Cell1729** [comment]
# 印刷用のcssの設定記録

## ディレクトリ

ディレクトリ`printer-setup`で印刷用のcssを管理する

```
.
└── static/
    ├── other static files
    ├── printer-setup/
    │   ├── flatTestMaker/
    │   │   ├── sample25-print-setup.css ... 問題数が25問のときの印刷微調整用css
    │   │   └── sample50-print-setup.css ... 問題数が50問のときの印刷微調整用css
    │   └── other print setup css files
    └── paper-setup.css ... A4用紙指定用のcss
```

## cssの読み込み

下記の通りに3つのcssを読み込ませる

- 印刷用紙のcss
- 印刷時に反映されるcss
- スクリーンに表示されるcss

```html
{% load static %}
    <!-- 印刷用紙の設定css -->
    <link href="{% static 'printer-setup/paper-setup.css' %}" media="print" rel="stylesheet" type="text/css">
    <!-- 印刷微調整用のcss -->
    <link href="{% static 'printer-setup/flatTestMaker/sample25-print-setup.css' %}" media="print" rel="stylesheet" type="text/css">
    <!-- スクリーンに表示用のcss -->
    <link rel="stylesheet" href="{% static 'flatTestMaker/css/generated_sample25_style.css' %}" media="screen">
```

印刷時に反映 ... `media ="print"`
スクリーン時に反映 ... `media = "screen"

## 微調整用cssの設定例

下記参照:
[sample25-print-setup.css](https://github.com/CloudWordCreator/CloudWordCreator/blob/develop/static/printer-setup/flatTestMaker/sample25-print-setup.css)

## その他 (問題と解答の横並びの設定)

```html
<div class='question-sheet'>...</div>
<div class='answer-sheet'>...</div>
```

`float: left(right);`で設定できる
`print-area`は変更したため一応メモ

```css
.print-area {
    border: 2px dashed #000; /* 印刷範囲を囲む線 */
    width: 100%; /* 印刷範囲の幅を設定 */

    position: relative;
    margin-top: 25px;
}

.question-sheet {
    float: left;
    width: 49%;
    border: 2px dashed #000; /* 印刷範囲を囲む線 */
}

.answer-sheet {
    break-before: page;
    float: right;
    width: 49%;
    border: 2px dashed #000; /* 印刷範囲を囲む線 */
}
```
